FROM php:8.2-apache
RUN apt-get update &&\
    apt-get install -y \
      libfreetype-dev \
      libjpeg62-turbo-dev \
      libpng-dev \
      libzip-dev \
      libpq-dev \
      unzip \
      zip \
      7zip \
      git \
      vim
RUN docker-php-ext-install gd pdo pdo_pgsql
RUN a2enmod rewrite
